# -*- coding: utf-8 -*-
"""SIS_CNN_PREDECIR.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ixGVKHiZKT7ODvYcLjSYU3Sqx22s92-Z
"""

!pip install tensorflow-addons

from google.colab import drive
drive.mount('/content/drive')

import numpy as np
import tensorflow_addons as tfa
import matplotlib.pyplot as plt
from tensorflow.keras.preprocessing import image
from keras.models import load_model
from keras import backend as K


radam = tfa.optimizers.RectifiedAdam()
ranger = tfa.optimizers.Lookahead(radam, sync_period=6, slow_step_size=0.5)

longitud, altura = 150, 150

modelo = ('/content/drive/MyDrive/SIS360/modelo/modelo.h5')
pesos_modelo = ('/content/drive/MyDrive/SIS360/modelo/pesos.h5')

#funciones para las métricas  que vamos a usar 

def recall_m(y_true, y_pred):
    true_positives = K.sum(K.round(K.clip(y_true * y_pred, 0, 1)))
    possible_positives = K.sum(K.round(K.clip(y_true, 0, 1)))
    recall = true_positives / (possible_positives + K.epsilon())
    return recall

def precision_m(y_true, y_pred):
    true_positives = K.sum(K.round(K.clip(y_true * y_pred, 0, 1)))
    predicted_positives = K.sum(K.round(K.clip(y_pred, 0, 1)))
    precision = true_positives / (predicted_positives + K.epsilon())
    return precision

def f1_m(y_true, y_pred):
    precision = precision_m(y_true, y_pred)
    recall = recall_m(y_true, y_pred)
    return 2*((precision*recall)/(precision+recall+K.epsilon()))

def prediction(image_name : str, model):
    labels = ['Downy mildew', 'Fresh Leaf', 'Gray mold', 'Leaf scars']
    img = image.load_img(image_name, target_size = (longitud,altura, 3))
    Y = image.img_to_array(img)
    
    X = np.expand_dims(Y, axis=0)
    val = model.predict(X)
    title = labels[np.argmax(val, axis=-1)[0]]
   
    plt.title(title)
    plt.imshow(plt.imread(image_name))

    plt.figure(figsize=(5,5))
    plt.bar(labels, val[0])
    plt.show()

cnn = load_model(modelo, custom_objects={"f1_m" : f1_m, "recall_m": recall_m, "precision_m": precision_m })

cnn.load_weights(pesos_modelo)

prediction('/content/drive/MyDrive/SIS360/validacion/Downy mildew/downymildew.  (15).jpg', cnn)

prediction('/content/drive/MyDrive/prueba_predicciones/gray-mold-of-sunflower.jpg', cnn)

prediction('/content/drive/MyDrive/SIS360/validacion/Fresh Leaf/fresh. (128).jpg', cnn)

prediction('/content/drive/MyDrive/SIS360/entrenamiento/Leaf scars/Leaf-wilt-caused-Verticillium-wilt-infection.png', cnn)